# Generated by Django 2.2.20 on 2021-06-09 16:54

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import lms.djangoapps.subscriptions.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('course_overviews', '0039_auto_20210406_1433'),
        ('enterprise', '0115_enterpriseanalyticsuser_historicalenterpriseanalyticsuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bundle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('slug', models.SlugField(blank=True, max_length=200)),
                ('description', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('courses', models.ManyToManyField(to='course_overviews.CourseOverview')),
                ('enterprise', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='enterprise.EnterpriseCustomer')),
            ],
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('billing_cycle', models.CharField(choices=[('month', 'MONTH'), ('year', 'YEAR'), ('onetime', 'ONE_TIME')], default=lms.djangoapps.subscriptions.models.BillingCycles('month'), max_length=10)),
                ('start_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('status', models.CharField(choices=[('active', 'ACTIVE'), ('inactive', 'INACTIVE'), ('expired', 'EXPIRED'), ('cancelled', 'CANCELLED')], default=lms.djangoapps.subscriptions.models.Statuses('active'), max_length=10)),
                ('license_count', models.IntegerField(default=1)),
                ('stripe_subscription_id', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('stripe_customer_id', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('stripe_price_id', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('enterprise', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='enterprise.EnterpriseCustomer')),
            ],
        ),
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'ACTIVE'), ('inactive', 'INACTIVE'), ('expired', 'EXPIRED'), ('cancelled', 'CANCELLED')], default=lms.djangoapps.subscriptions.models.Statuses('active'), max_length=10)),
                ('description', models.CharField(blank=True, choices=[('CREATED', 'CREATE'), ('RENEWAL', 'RENEW'), ('CANCELLED', 'CANCEL'), ('EXPIRED', 'EXPIRE')], default=None, max_length=10, null=True)),
                ('license_count', models.IntegerField()),
                ('stripe_invoice_id', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('ecommerce_trans_id', models.IntegerField(blank=True, default=None, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subscriptions.Subscription')),
            ],
        ),
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('slug', models.SlugField(blank=True, max_length=200)),
                ('image_url', models.URLField(blank=True, max_length=255)),
                ('description', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('ecommerce_prod_id', models.IntegerField(blank=True, default=None, null=True, verbose_name='Ecommerce Product ID')),
                ('ecommerce_stockrecord_id_month', models.IntegerField(blank=True, default=None, null=True)),
                ('ecommerce_stockrecord_id_year', models.IntegerField(blank=True, default=None, null=True)),
                ('ecommerce_stockrecord_id_one_time', models.IntegerField(blank=True, default=None, null=True)),
                ('grace_period', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('is_utap_supported', models.BooleanField(default=False)),
                ('price_month', models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=6, null=True)),
                ('price_onetime', models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=6, null=True)),
                ('price_year', models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=6, null=True)),
                ('stripe_prod_id', models.CharField(max_length=50, verbose_name='Stripe Product ID')),
                ('stripe_price_id_month', models.CharField(blank=True, max_length=50, null=True, verbose_name='Stripe Price ID (month)')),
                ('stripe_price_id_year', models.CharField(blank=True, max_length=50, null=True, verbose_name='Stripe Product ID (year)')),
                ('valid_until', models.DateTimeField(blank=True, default=None, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bundle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='subscriptions.Bundle')),
                ('enterprise', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='enterprise.EnterpriseCustomer')),
            ],
        ),
        migrations.AddField(
            model_name='subscription',
            name='subscription_plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subscriptions.SubscriptionPlan'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='License',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subscriptions.Subscription')),
                ('user', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
