# Generated by Django 2.2.20 on 2021-06-09 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscriptionplan',
            old_name='ecommerce_stockrecord_id_one_time',
            new_name='ecommerce_stockrecord_id_onetime',
        ),
    ]
