# Generated by Django 2.2.20 on 2021-06-10 20:51

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0002_auto_20210609_1921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bundle',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, default=None, null=True),
        ),
    ]
