# Generated by Django 2.2.20 on 2021-06-10 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0003_auto_20210610_2051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptionplan',
            name='image_url',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
