# Generated by Django 2.2.20 on 2021-06-15 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0004_auto_20210610_2106'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transactions',
            name='ecommerce_trans_id',
        ),
        migrations.AddField(
            model_name='transactions',
            name='ecommerce_order_number',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
    ]
