# Generated by Django 2.2.20 on 2021-06-20 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0006_auto_20210617_1204'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscriptionplan',
            name='grace_period',
        ),
        migrations.RemoveField(
            model_name='transactions',
            name='ecommerce_order_number',
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='ecommerce_prod_id_month',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='ecommerce_prod_id_onetime',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='ecommerce_prod_id_year',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='transactions',
            name='ecommerce_trans_id',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
