# Generated by Django 2.2.20 on 2021-06-20 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0007_auto_20210620_0713'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionplan',
            name='image_upload',
            field=models.ImageField(default=None, upload_to='banner/lms/plans'),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='image_url',
            field=models.TextField(blank=True, default=''),
        ),
    ]
