# Generated by Django 2.2.20 on 2021-06-20 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0008_auto_20210620_0912'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptionplan',
            name='image_upload',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='banner/lms/plans'),
        ),
    ]
