# Generated by Django 2.2.20 on 2021-06-20 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0009_auto_20210620_0913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptionplan',
            name='image_upload',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='subscriptions/plan'),
        ),
    ]
