# Generated by Django 2.2.20 on 2021-06-20 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0010_auto_20210620_0917'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscriptionplan',
            name='image_url',
        ),
    ]
