# Generated by Django 2.2.20 on 2021-06-20 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0011_remove_subscriptionplan_image_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transactions',
            name='ecommerce_trans_id',
        ),
        migrations.AddField(
            model_name='transactions',
            name='ecommerce_order_number',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
    ]
