# Generated by Django 2.2.20 on 2021-06-09 14:08

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0011_auto_20210527_0732'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bundle',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
