# Generated by Django 2.2.19 on 2021-06-09 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banner', '0005_auto_20210608_1511'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='link_type',
            field=models.CharField(choices=[('about', 'ABOUT'), ('bundle', 'BUNDLE'), ('subscription', 'SUBSCRIPTION'), ('external', 'EXTERNAL')], default='ABOUT', max_length=20),
        ),
    ]
