# Generated by Django 2.2.19 on 2021-05-12 06:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('course_overviews', '0039_auto_20210406_1433'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseTagType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('display_name', models.CharField(max_length=255)),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('is_enabled', models.BooleanField(default=True)),
                ('sector', models.CharField(blank=True, max_length=255, null=True)),
                ('platform', models.CharField(choices=[('mobile', 'MOBILE'), ('web', 'WEB'), ('both', 'BOTH')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CourseTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course_over_view', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crs_ovr_view', to='course_overviews.CourseOverview')),
                ('course_tag_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_tag_type', to='course_tag.CourseTagType')),
            ],
        ),
    ]
