# Generated by Django 2.2.19 on 2021-06-10 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_tag', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursetagtype',
            name='sequence',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
