# Generated by Django 2.2.20 on 2021-06-05 01:48

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import lms.djangoapps.custom_form_app.custom_reg_form.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_squashed_0007_historicalorganization'),
        ('course_overviews', '0039_auto_20210406_1433'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserExtraInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_birth', models.DateField(default=datetime.date(2000, 1, 1), validators=[lms.djangoapps.custom_form_app.custom_reg_form.models.age_validator], verbose_name='Date of birth')),
                ('nric', models.CharField(blank=True, max_length=100, null=True, verbose_name='NRIC')),
                ('industry', models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='users_industry', to='course_overviews.Category')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='instructor_org', to='organizations.Organization')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_extra_info', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
