# Generated by Django 2.2.20 on 2021-05-31 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lhub_ecommerce_offer', '0009_coupon_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='incentive_type',
            field=models.CharField(blank=True, choices=[('Percentage', "Discount is a percentage off of the product's value"), ('Absolute', "Discount is a fixed amount off of the product's value")], max_length=250, verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='incentive_type',
            field=models.CharField(blank=True, choices=[('Percentage', "Discount is a percentage off of the product's value"), ('Absolute', "Discount is a fixed amount off of the product's value")], max_length=250, verbose_name='Type'),
        ),
    ]
